### Numpy VS Python list


In [14]:
# Creating two list of 10*10^6 & 10*10^6 to 20^10^6 element and adding both ans storing in c

a=[i for i in range(10000000)]
b=[i for i in range(10000000,20000000)]

c=[]

import time

start=time.time()

for i in range(len(a)):
    c.append(a[i]+b[i])

print(time.time()-start)



1.191044569015503


In [15]:
# Creating a numpy for same operation
 
import numpy as np

a=np.arange(10000000)
b=np.arange(10000000,20000000)
start=time.time()
c=a+b
print(time.time()-start)

print(c)


0.0958871841430664
[10000000 10000002 10000004 ... 29999994 29999996 29999998]


In [16]:
1.191044569015503/0.0958871841430664

#numpy is usually 9.6 times faster then on this operation


12.421311353125466

## memory
#### checking memory of list vs numpy array

In [6]:
a =[i for i in range(10000000)]
import sys

size=sys.getsizeof(a)

print((size/1024)/1024)

84.96776580810547


In [22]:
a=np.arange(10000000)
size=sys.getsizeof(a)
print((size/1024)/1024)

76.29405212402344


# Advance Indexing
#### fancy and boolean 


In [54]:
#fancy

a=np.arange(12).reshape(4,3)
print(a)
a[[0,1,2,3],[0,1,2,1]] # passing a list [row,row],[col],[col] and then providing the index of row and column
#also row para and column para should be same

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([ 0,  4,  8, 10])

In [55]:
#boolean

a=np.random.randint(1,100,24).reshape(6,4)
print(a)

[[64 73  4 12]
 [43 44  2 24]
 [58 32 58 37]
 [61 75  5  2]
 [66 13 36 29]
 [33 24 31 78]]


In [56]:
#find all digit greater then 50
#we can use the boolean matrix as mask and remove the non required element
a>50

array([[ True,  True, False, False],
       [False, False, False, False],
       [ True, False,  True, False],
       [ True,  True, False, False],
       [ True, False, False, False],
       [False, False, False,  True]])

In [57]:
a[a>50]

array([64, 73, 58, 58, 61, 75, 66, 78], dtype=int32)

In [58]:
a % 2 == 0

array([[ True, False,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False,  True],
       [ True, False,  True, False],
       [False,  True, False,  True]])

In [59]:
a[a%2==0]

array([64,  4, 12, 44,  2, 24, 58, 32, 58,  2, 66, 36, 24, 78],
      dtype=int32)

In [60]:
(a>50) & (a%2==0)

array([[ True, False, False, False],
       [False, False, False, False],
       [ True, False,  True, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False,  True]])

In [61]:
a[(a>50) & (a%2==0)]

array([64, 58, 58, 66, 78], dtype=int32)