# First and foremost :smile: step is to Import

In [3]:
import numpy as np

### creating a vector(1D)

In [4]:
a=np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


### CREATING A 2D ARRAY

In [5]:
b=np.array([[1,2,3,4],[1,2,3,4]])
print(b)

[[1 2 3 4]
 [1 2 3 4]]


### creating 3d array


In [6]:
nf=np.array([[[1,2,3],[4,5,6],[7,8,9]],
             [[11,12,13],[14,15,16],[17,18,19]]])
print(nf[0])
print(nf[1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


# Different Methods to generate array
### we can save generated array in an variable and access the invidiual row and column 
### by var[index] and also invidual element by var[ind][ind]

In [7]:
a5=np.arange(20)
for x in a5:
    if(x%2==0):
        print(x,end=" ")    

0 2 4 6 8 10 12 14 16 18 

In [8]:
#reshape(Row,column)
a6=np.arange(16).reshape(4,4)
a6.shape
print(a6)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [9]:
np.ones((3,4)) #3 rows and 4 column

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((4,3)) #4 raw and 3 column 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
a7=np.random.random((3,4))
print(a7*10) #values genrated are from 0<x<1, so multiplied by 10.

[[2.84587439 5.94969875 4.38269609 6.39904332]
 [1.64984852 6.97730646 9.43456901 0.21087406]
 [0.33581509 6.72218528 4.619602   9.23866637]]


In [13]:
#linearspace
#genrates equal points between two points
np.linspace(0,70,10)  #(lower range,upper range,number of items)

array([ 0.        ,  7.77777778, 15.55555556, 23.33333333, 31.11111111,
       38.88888889, 46.66666667, 54.44444444, 62.22222222, 70.        ])

## ARRAY ATTRIBUTE
### ndim
### size
### itemsize
### shape
### dtype

In [14]:
a1=np.arange(10,dtype=np.int32) #changed the data type
a2=np.arange(12).reshape((3,4))
a3=np.arange(8).reshape(2,2,2)


In [15]:
# ndim to find the dimension of the array 

a1.ndim

1

In [16]:
a2.ndim


2

In [17]:
a3.ndim

3

In [18]:
# shape to find the shape of the array 

a1.shape

(10,)

In [19]:
a2.shape

(3, 4)

In [20]:
# (number of matrix,rows,column)
a3.shape

(2, 2, 2)

In [21]:
# size of array

a1.size

10

In [22]:
a2.size

12

In [23]:
a3.size

8

In [24]:
# itemsize tells the size of the element inside the array eg int32,int64,float
a1.itemsize #as changed above to int32 the size is reduced to 4bytes

4

In [25]:
a2.itemsize

8

In [26]:
a3.itemsize #here all the dtypes float and int 64 are showing same because of its default setting

8

## Changing the dtype

In [27]:
# Before Changing the type
a3.dtype

dtype('int64')

In [28]:
a3=a3.astype(np.int32)
a3.dtype

dtype('int32')

In [29]:
print("2 2D ARRAY OF SHAPE 2*2")
print("data type:-",a3.dtype)
print(a3) 



2 2D ARRAY OF SHAPE 2*2
data type:- int32
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


# ARRAY OPERATION

#### SCALER OPERATION

In [30]:
a10=np.random.random(9).reshape(3,3)
a10

array([[0.33768193, 0.83872739, 0.86757184],
       [0.32051241, 0.52943132, 0.30473679],
       [0.86309751, 0.91238661, 0.97557982]])

In [31]:
# array with scaler 
# *,/,+,%,**
a9=np.arange(9).reshape(3,3)*10
print(a9)

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]


In [32]:
a9+2

array([[ 2, 12, 22],
       [32, 42, 52],
       [62, 72, 82]])

In [33]:
a9//2

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

#### RELATIONAL

In [34]:
# >,<,>=,<=,==
a9>15

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [35]:
a9<15

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [36]:
a9==1

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

# Vector operation

### mixed example of relational and operations

In [37]:
a9

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [38]:
a10

array([[0.33768193, 0.83872739, 0.86757184],
       [0.32051241, 0.52943132, 0.30473679],
       [0.86309751, 0.91238661, 0.97557982]])

In [39]:
# between array operation
a9+a10


array([[ 0.33768193, 10.83872739, 20.86757184],
       [30.32051241, 40.52943132, 50.30473679],
       [60.86309751, 70.91238661, 80.97557982]])

In [40]:
a9-a10

array([[-0.33768193,  9.16127261, 19.13242816],
       [29.67948759, 39.47056868, 49.69526321],
       [59.13690249, 69.08761339, 79.02442018]])

In [41]:
a9*a10

array([[ 0.        ,  8.38727393, 17.35143683],
       [ 9.61537218, 21.17725271, 15.2368397 ],
       [51.78585058, 63.8670625 , 78.04638521]])

In [42]:
a9/a10

array([[  0.        ,  11.92282509,  23.05284594],
       [ 93.60012108,  75.55276512, 164.07601901],
       [ 69.51705841,  76.7218627 ,  82.00251661]])

In [43]:
a9//a10

array([[  0.,  11.,  23.],
       [ 93.,  75., 164.],
       [ 69.,  76.,  82.]])

In [44]:
a9>a10

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [45]:
a9<a10

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [46]:
a9==a10

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

### ARRAY FUNCTION

In [47]:
b1=np.random.random((3,3))
b1=np.round(b1*100)
b1

array([[ 1., 58., 96.],
       [91., 37., 38.],
       [69., 75., 88.]])

#### min/max/sum/prod

In [48]:
# axis
# 0-> column,1-> rows
np.max(b1)

np.float64(96.0)

In [49]:
np.min(b1)

np.float64(1.0)

In [50]:
np.sum(b1)

np.float64(553.0)

In [51]:
np.prod(b1)

np.float64(324428475571200.0)

In [52]:
np.prod(b1,axis=0)

array([  6279., 160950., 321024.])

In [53]:
np.prod(b1,axis=1)

array([  5568., 127946., 455400.])

#### Median,Std,Mean,Var


##### can also calculate median and mean 

In [54]:

np.median(b1)

np.float64(69.0)

In [55]:
np.mean(b1)

np.float64(61.44444444444444)

In [56]:
np.std(b1)

np.float64(29.488646067827194)

In [57]:
np.var(b1)

np.float64(869.5802469135803)

#### Log and expo Function

In [58]:
np.log(b1)

array([[0.        , 4.06044301, 4.56434819],
       [4.51085951, 3.61091791, 3.63758616],
       [4.2341065 , 4.31748811, 4.47733681]])

In [59]:
np.exp(b1)

array([[2.71828183e+00, 1.54553894e+25, 4.92345829e+41],
       [3.31740010e+39, 1.17191424e+16, 3.18559318e+16],
       [9.25378173e+29, 3.73324200e+32, 1.65163625e+38]])

#### DOT PRODUCT

In [60]:
b2=np.array([[1,2,3,4],
             [5,6,7,8],
             [1,2,3,4]])
b2.shape

(3, 4)

In [61]:
b1.shape

(3, 3)

In [62]:
np.dot(b1,b2)

array([[ 387.,  542.,  697.,  852.],
       [ 314.,  480.,  646.,  812.],
       [ 532.,  764.,  996., 1228.]])

### ceil and floor 


##### ceil gives upper rouund of while floor gives down ans correspond to its name

In [63]:
d=np.array([1.1,1.2,2,3])
print(np.ceil(d))

[2. 2. 2. 3.]


In [69]:
d=np.array([1.1,1.2,2,3])
print(np.floor(d))

[1. 1. 2. 3.]


## INDEXING

In [64]:
d1=np.array([1,2,3,4,5,6])
d1.ndim

1

In [65]:
d2=np.array([[1,2,3,4],
             [5,6,7,8],
             [1,2,3,4]])
d2.ndim

2

In [66]:
#d2[row,column]
d2[1,1] # or d2[1][1]

np.int64(6)

In [67]:
d3=np.array(
[
    [
        [1,2,3,4],[5,6,7,8]
    ],
    [
        [9,10,11,12],[13,14,15,16]
    ]
])
d3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [68]:
#arr[1st half or 2nd half,row,column]
# for 16 it lies in second so 1 then 1 st row 3rd column
d3[1,1,3]

np.int64(16)

# Stacking and Splitting


### a) Horizontal Stacking(hstack)
##### combines array side by side

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.hstack((a, b)))



[1 2 3 4 5 6]


### 

### b) Vertical Stacking(vstack)
#### combines arrays vertically

In [71]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack((a, b)))

[[1 2 3]
 [4 5 6]]


### c) Column stack
#### makes arrays in columns

In [72]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.column_stack((a, b)))

[[1 4]
 [2 5]
 [3 6]]


# Splitting Array
#### Splits one array into multiple parts

In [73]:
arr = np.array([1, 2, 3, 4, 5, 6])

result = np.split(arr, 3)

print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]
