### SORTING

In [94]:


import numpy as np

a=np.random.randint(1,100,15)
print(a)

np.sort(a)

np.sort(a)[::-1] #for descending


[14 98 37 89 25 36 72 36 80 51 75 38 24 98 93]


array([98, 98, 93, 89, 80, 75, 72, 51, 38, 37, 36, 36, 25, 24, 14],
      dtype=int32)

In [95]:
b=np.arange(12).reshape(3,4)
print(b)

np.sort(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### APPENED

In [96]:

np.append(a,200)

array([ 14,  98,  37,  89,  25,  36,  72,  36,  80,  51,  75,  38,  24,
        98,  93, 200])

In [97]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[ 0.,  1.,  2.,  3.,  1.],
       [ 4.,  5.,  6.,  7.,  1.],
       [ 8.,  9., 10., 11.,  1.]])

### conacatenate

In [99]:
c=np.arange(10,22).reshape(3,4)
print(c)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [100]:
np.concatenate((b,c),axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [101]:
np.concatenate((b,c),axis=1)

array([[ 0,  1,  2,  3, 10, 11, 12, 13],
       [ 4,  5,  6,  7, 14, 15, 16, 17],
       [ 8,  9, 10, 11, 18, 19, 20, 21]])

### unique value

In [102]:
np.unique(a)

array([14, 24, 25, 36, 37, 38, 51, 72, 75, 80, 89, 93, 98], dtype=int32)

### EXPAND-DIMENSION
#### expand dimension of the array

In [103]:
# 0 = column
a


array([14, 98, 37, 89, 25, 36, 72, 36, 80, 51, 75, 38, 24, 98, 93],
      dtype=int32)

In [104]:
a.shape

(15,)

In [105]:
np.expand_dims(a,axis=1)

array([[14],
       [98],
       [37],
       [89],
       [25],
       [36],
       [72],
       [36],
       [80],
       [51],
       [75],
       [38],
       [24],
       [98],
       [93]], dtype=int32)

In [106]:
np.expand_dims(a,axis=0)

array([[14, 98, 37, 89, 25, 36, 72, 36, 80, 51, 75, 38, 24, 98, 93]],
      dtype=int32)

### where
#### return index where condition statisfy

In [107]:
a

array([14, 98, 37, 89, 25, 36, 72, 36, 80, 51, 75, 38, 24, 98, 93],
      dtype=int32)

In [108]:
np.where(a>50) 

(array([ 1,  3,  6,  8,  9, 10, 13, 14]),)

In [109]:
np.where(a>50,0,a) 

array([14,  0, 37,  0, 25, 36,  0, 36,  0,  0,  0, 38, 24,  0,  0],
      dtype=int32)

In [110]:
np.where(a%2==0,0,a)

array([ 0,  0, 37, 89, 25,  0,  0,  0,  0, 51, 75,  0,  0,  0, 93],
      dtype=int32)

### ARGMAX & ARGMIN
#### index element  of the max

In [111]:
np.argmax(a)

np.int64(1)

In [112]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
np.argmax(b,axis=0)

array([2, 2, 2, 2])

### cumsum
#### cumulative sum of the array


In [114]:
a

array([14, 98, 37, 89, 25, 36, 72, 36, 80, 51, 75, 38, 24, 98, 93],
      dtype=int32)

In [115]:
np.cumsum(a)

array([ 14, 112, 149, 238, 263, 299, 371, 407, 487, 538, 613, 651, 675,
       773, 866])

In [116]:
y=np.array([1,2,3,4,5])
np.cumprod(y)

array([  1,   2,   6,  24, 120])

### PERCENTILE

In [117]:
a

array([14, 98, 37, 89, 25, 36, 72, 36, 80, 51, 75, 38, 24, 98, 93],
      dtype=int32)

In [118]:
np.percentile(a,90)

np.float64(96.0)

### HISTOGRAM
#### FREQUENCY COUNT

In [119]:
a

array([14, 98, 37, 89, 25, 36, 72, 36, 80, 51, 75, 38, 24, 98, 93],
      dtype=int32)

In [120]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 1, 2, 4, 0, 1, 0, 2, 2, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### CORRELATION
#### tells the col relation between two variables

In [121]:
sal=np.array([10000,20000,30000,40000])
exp=np.array([1,3,4,5])

np.corrcoef(sal,exp)

array([[1.        , 0.98270763],
       [0.98270763, 1.        ]])

### IS.in
#### search multiple items in array

In [122]:
a

array([14, 98, 37, 89, 25, 36, 72, 36, 80, 51, 75, 38, 24, 98, 93],
      dtype=int32)

In [123]:
items=[2,3,4,2,3,4,5,3,2,5,2,2,4,25,6,6,464,77,8,6,7,7,65,4,7,354,353,7,75,7,74,7,457,47,47,45667,4574]
a[np.isin(a,items)]

array([25, 75], dtype=int32)

### flip

In [124]:
a

array([14, 98, 37, 89, 25, 36, 72, 36, 80, 51, 75, 38, 24, 98, 93],
      dtype=int32)

In [125]:
np.flip(a)

array([93, 98, 24, 38, 75, 51, 80, 36, 72, 36, 25, 89, 37, 98, 14],
      dtype=int32)

### put
#### change the array by giving index and vlaue (permanent change)

In [126]:
a


array([14, 98, 37, 89, 25, 36, 72, 36, 80, 51, 75, 38, 24, 98, 93],
      dtype=int32)

In [127]:
np.put(a,[0],[9])

In [128]:
# if we refresh all the a its 0 will be change to 9
a

array([ 9, 98, 37, 89, 25, 36, 72, 36, 80, 51, 75, 38, 24, 98, 93],
      dtype=int32)

# SET FUNCTION
### np.union1d
### np.intersect1d
### np.setdiff1d
### np.setxor1d
### np.in1d

In [129]:
u=[1,2,3,4,5]
z=[3,4,5,6,7,8]

In [130]:
np.union1d(u,z)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [131]:
np.intersect1d(u,z)

array([3, 4, 5])

In [132]:
np.setdiff1d(u,z)

array([1, 2])

In [133]:
np.setdiff1d(u,z)

array([1, 2])

In [134]:
np.setxor1d(u,z)

array([1, 2, 6, 7, 8])

In [135]:
a

array([ 9, 98, 37, 89, 25, 36, 72, 36, 80, 51, 75, 38, 24, 98, 93],
      dtype=int32)

In [137]:
np.clip(a,a_min=25,a_max=75)

array([25, 75, 37, 75, 25, 36, 72, 36, 75, 51, 75, 38, 25, 75, 75],
      dtype=int32)